import React from 'react';
import { notFound } from 'next/navigation';
import fs from 'fs';
import path from 'path';
import { ScoredReport } from '@/lib/types';
import ScoreGauge from '@/components/ScoreGauge';
import TierAccordion from '@/components/TierAccordion';
import GapTable from '@/components/GapTable';
import Tier5Panel from '@/components/Tier5Panel';
import { FileText, Mail, Link as LinkIcon } from 'lucide-react';
import Link from 'next/link';

export async function generateStaticParams() {
  return [
    { slug: 'kraken' },
    { slug: 'coinbase-exchange' },
    { slug: 'coinbase-derivatives' },
  ];
}

import os from 'os';

async function getScoredReport(slug: string): Promise<ScoredReport | null> {
  // Try static audits folder first
  let filePath = path.join(process.cwd(), 'audits', slug, 'scored_report.json');
  
  if (!fs.existsSync(filePath)) {
    // Fallback to dynamic tmp folder generated by live /api/score
    filePath = path.join(os.tmpdir(), slug, 'scored_report.json');
    if (!fs.existsSync(filePath)) {
      return null;
    }
  }
  
  const fileContents = fs.readFileSync(filePath, 'utf8');
  return JSON.parse(fileContents);
}

export default async function AuditPage({ params }: { params: { slug: string } }) {
  const report = await getScoredReport(params.slug);
  if (!report) notFound();

  return (
    <div className="max-w-7xl mx-auto px-4 py-12">
      {/* Header Info */}
      <div className="mb-12">
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="px-2 py-0.5 bg-navy-dark text-white text-[10px] font-bold rounded uppercase tracking-wider">Certified Audit</span>
              <span className="text-sm text-slate-400 font-medium">Draft v1.1 Analysis</span>
            </div>
            <h1 className="text-4xl md:text-5xl font-black text-slate-900 tracking-tight mb-2">
              {report.exchange_name} <span className="text-slate-400">Readiness Score</span>
            </h1>
            {params.slug === 'coinbase-derivatives' && (
              <div className="bg-amber-50 border-amber-200 text-amber-800 text-sm p-3 rounded-lg mt-4 mb-4">
                Coinbase Derivatives Exchange is a CFTC-regulated Designated Contract Market. FIX connectivity requires approved firm onboarding. Audit based on public documentation only.
              </div>
            )}
            <div className="flex flex-wrap items-center gap-x-6 gap-y-2 text-sm font-medium text-slate-500">
              <div className="flex items-center gap-1.5 font-bold uppercase tracking-wider text-[10px]">
                <span className="text-slate-400">Audited:</span> {report.audit_date}
              </div>
            </div>
          </div>
          
          <div className="flex items-center gap-3">
            <Link 
              href={`/audit/${params.slug}/report`}
              target="_blank"
              className="px-6 h-12 bg-white border border-slate-200 text-slate-700 rounded-xl font-bold flex items-center gap-2 hover:bg-slate-50 transition-all shadow-sm"
            >
              <FileText className="w-4 h-4" />
              Download RoE document
            </Link>
            <button className="px-6 h-12 bg-navy-dark text-white rounded-xl font-bold flex items-center gap-2 hover:bg-slate-800 transition-all shadow-lg shadow-navy-dark/10">
              <Mail className="w-4 h-4" />
              Email Report
            </button>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className="lg:col-span-5 space-y-12">
          <div className="bg-white border border-slate-200 rounded-3xl p-8 shadow-sm">
            <h3 className="text-center text-xs font-bold text-slate-400 uppercase tracking-widest mb-4">Overall Score</h3>
            <ScoreGauge score={report.total_score} grade={report.grade} />
            <div className="mt-8 space-y-6">
              {Object.entries(report.tier_scores).map(([key, tier], index) => (
                <div key={key}>
                  <div className="flex justify-between items-end mb-2">
                    <span className="text-xs font-bold text-slate-500 uppercase tracking-wider">Tier {index + 1}: {tier.label}</span>
                    <span className="text-sm font-bold text-slate-900">{tier.earned}/{tier.available}</span>
                  </div>
                  <div className="w-full h-2 bg-slate-100 rounded-full overflow-hidden">
                    <div className="h-full bg-navy-dark rounded-full transition-all duration-1000" style={{ width: `${tier.pct}%` }} />
                  </div>
                </div>
              ))}
            </div>
          </div>
          <GapTable gaps={report.gap_summary} />
        </div>
        <div className="lg:col-span-7 space-y-12">
          <TierAccordion tierScores={report.tier_scores} details={report.full_detail} />
          {report.tier5_results && <Tier5Panel results={report.tier5_results} />}
        </div>
      </div>
    </div>
  );
}
