'use client';

import React from 'react';
import { marked } from 'marked';

interface PrintReportProps {
  content: string;
  exchangeName: string;
}

const PrintReport: React.FC<PrintReportProps> = ({ content, exchangeName }) => {
  // Configure marked if necessary (standard is fine for now)
  const htmlContent = marked.parse(content);

  return (
    <div className="bg-white min-h-screen">
      {/* Screen only banner */}
      <div className="print:hidden bg-navy-dark text-white p-4 text-center sticky top-0 z-50">
        <p className="font-medium">
          RoE Document for <span className="font-bold">{exchangeName}</span>. 
          Use <kbd className="bg-white/10 px-1 rounded">Cmd+P</kbd> or <kbd className="bg-white/10 px-1 rounded">Ctrl+P</kbd> to Save as PDF.
        </p>
        <button 
          onClick={() => window.print()}
          className="mt-2 bg-white text-navy-dark px-4 py-1.5 rounded-md text-sm font-bold hover:bg-slate-100 transition-colors"
        >
          Print / Save as PDF
        </button>
      </div>

      {/* Print content */}
      <div className="max-w-4xl mx-auto px-10 py-16 print:px-0 print:py-0 bg-white">
        <div 
          className="prose prose-slate max-w-none 
            prose-headings:font-serif prose-headings:font-bold prose-headings:text-slate-900
            prose-p:font-serif prose-p:leading-relaxed prose-p:text-slate-800
            prose-strong:font-bold prose-strong:text-slate-900
            prose-code:font-mono prose-code:text-navy-dark prose-code:bg-slate-50 prose-code:px-1 prose-code:rounded
            print:prose-p:text-sm print:prose-headings:text-lg
            [&>h1]:text-3xl [&>h1]:border-b [&>h1]:border-slate-200 [&>h1]:pb-4 [&>h1]:mb-8
            [&>h2]:text-xl [&>h2]:border-b [&>h2]:border-slate-100 [&>h2]:pb-2 [&>h2]:mt-12 [&>h2]:mb-6 [&>h2]:break-before-page
          "
          dangerouslySetInnerHTML={{ __html: htmlContent }}
        />
        
        <div className="mt-16 pt-8 border-t border-slate-200 text-xs text-slate-400 font-serif italic text-center print:mt-8">
          Generated by CryptoFIX Institutional Readiness Auditor — Opound LLC
        </div>
      </div>

      <style jsx global>{`
        @media print {
          nav, footer, .print-hidden {
            display: none !important;
          }
          @page {
            margin: 1in;
            size: letter;
          }
          body {
            background: white !important;
            color: black !important;
          }
          .prose {
            max-width: none !important;
          }
        }
      `}</style>
    </div>
  );
};

export default PrintReport;
