import fs from 'fs';
import path from 'path';
import os from 'os';
import { ScoredReport } from './types';

export async function getScoredReport(slug: string): Promise<ScoredReport | null> {
  // Try static audits folder first
  let filePath = path.join(process.cwd(), 'audits', slug, 'scored_report.json');
  
  if (!fs.existsSync(filePath)) {
    // Fallback to dynamic tmp folder generated by live /api/score
    filePath = path.join(os.tmpdir(), slug, 'scored_report.json');
    if (!fs.existsSync(filePath)) {
      return null;
    }
  }
  
  try {
    const fileContents = fs.readFileSync(filePath, 'utf8');
    return JSON.parse(fileContents);
  } catch (error) {
    console.error(`Error reading report for ${slug}:`, error);
    return null;
  }
}
